name: Homebrew Deploy

on:
  release:
    types: [published, released]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Clone homebrew-zvm
        run: git clone https://github.com/gaetschwartz/homebrew-zvm homebrew-zvm
      - name: Clone zvm
        run: git clone https://github.com/gaetschwartz/zvm zvm-repo
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Update zvm.rb
        run: |
          brew tap gaetschwartz/zvm
          brew developer on
          python zvm-repo/ci/update_formula.py zvm homebrew-zvm/zvm.rb
      - name: Commit the changes to zvm.rb
        working-directory: homebrew-zvm
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add zvm.rb
          tag_name=$(brew livecheck --json zvm | jq ".[0].version.latest" -r)
          git commit -m "Update zvm to $tag_name"
      - name: Push the changes
        working-directory: homebrew-zvm
        run: |
          git push https://${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}@github.com/gaetschwartz/homebrew-zvm.git HEAD:master
