name: Scoop Deploy

on:
  release:
    types: [published, released]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Scoop
    runs-on: windows-latest
    steps:
      - name: Clone scoop
        run: git clone https://github.com/ScoopInstaller/Scoop scoop
      - name: Clone scoop-zvm
        uses: actions/checkout@v3
        with:
          repository: gaetschwartz/scoop-zvm
          path: scoop-zvm
      - name: Update zvm.json
        run: scoop/bin/checkver.ps1 -Update -ForceUpdate scoop-zvm/zvm.json
      - name: Commit the changes to zvm.json
        working-directory: scoop-zvm
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add zvm.json
          $tag_name = (Get-Content .\zvm.json -Raw | ConvertFrom-Json).version
          git commit -m "Update zvm to $tag_name"
      - name: Push the changes
        working-directory: scoop-zvm
        run: |
          git push https://${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}@github.com/gaetschwartz/scoop-zvm.git HEAD:master
