name: Homebrew Deploy

on:
  workflow_dispatch:
  release:
    types: [published, released]

jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Homebrew/actions/bump-formulae@master
        with:
          formulae: zvm
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
