name: Homebrew Deploy

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  deploy-scoop:
    name: Deploy Scoop
    runs-on: windows-latest
    steps:
      - name: Clone scoop
        run: git clone https://github.com/ScoopInstaller/Scoop scoop
      - name: Clone scoop-zvm
        run: git clone https://github.com/gaetschwartz/scoop-zvm scoop-zvm
      - name: Update zvm.json
        run: scoop/bin/checkver.ps1 -Update -ForceUpdate scoop-zvm/zvm.json
      - name: Commit the changes to zvm.json
        working-directory: scoop-zvm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add zvm.json
          $tag_name = (Get-Content .\zvm.json -Raw | ConvertFrom-Json).version
          git commit -m "Update zvm to $tag_name"
          git remote set-url --push origin https://gaetschwartz:$GITHUB_TOKEN@github.com/gaetschwartz/scoop-zvm.git
      - name: Push the changes
        working-directory: scoop-zvm
        run: git push
  deploy-homebrew:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Clone homebrew-zvm
        run: git clone https://github.com/gaetschwartz/homebrew-zvm homebrew-zvm
      - name: Clone zvm
        run: git clone https://github.com/gaetschwartz/zvm zvm-repo
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Update zvm.rb
        run: |
          brew tap gaetschwartz/zvm
          brew developer on
          python zvm-repo/ci/update_formula.py zvm homebrew-zvm/zvm.rb
      - name: Commit the changes to zvm.rb
        working-directory: homebrew-zvm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add zvm.rb
          tag_name=$(brew livecheck --json zvm | jq ".[0].version.latest" -r)
          git commit -m "Update zvm to $tag_name"
          git remote set-url --push origin https://gaetschwartz:$GITHUB_TOKEN@github.com/gaetschwartz/homebrew-zvm.git
      - name: Push the changes
        working-directory: homebrew-zvm
        run: git push
