name: Homebrew Deploy

on:
  release:
    types: [published, released]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Clone zvm
        uses: actions/checkout@v2
        with:
          repository: gaetschwartz/zvm
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Extract formula path
        id: extract-formula-path
        run: |
          brew tap gaetschwartz/zvm
          # get formula path
          formula_path=$(brew formula zvm)
          # save output
          echo "formula_path=$formula_path" >> $GITHUB_ENV
      - name: Extract version
        id: extract-version
        run: |
          tag_name=$(git describe --tags --abbrev=0)
          echo "tag-name=$tag_name" >> $GITHUB_ENV
      - name: Bump Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: zvm
          formula-path: ${{ steps.extract-formula-path.outputs.formula_path }}
          homebrew-tap: gaetschwartz/zvm
          base-branch: master
          download-url: https://github.com/gaetschwartz/zvm/releases/download/${{ steps.extract-version.outputs.tag-name }}/zvm-x86_64-macos
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
