on:
  push:
    branches:
      - staging

name: Build and deploy on staging

jobs:
  build-staging:
    strategy:
      matrix:
        target:
          - x86_64-linux
          - x86_64-macos
          - aarch64-linux
          - aarch64-macos
          - x86_64-windows
          - aarch64-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build -Doptimize=ReleaseSafe -Dtarget=${{matrix.target}}
      - name: Rename binary
        if: ${{ !endsWith(matrix.target, '-windows') }}
        run: mv zig-out/bin/zvm zig-out/bin/zvm-${{matrix.target}}
      - name: Rename binary (windows)
        if: ${{ endsWith(matrix.target, '-windows') }}
        run: mv zig-out/bin/zvm.exe zig-out/bin/zvm-${{matrix.target}}.exe
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        if: ${{ !endsWith(matrix.target, '-windows') }}
        with:
          name: zvm-${{matrix.target}}
          path: zig-out/bin/zvm-${{matrix.target}}
      - uses: actions/upload-artifact@v3
        name: Upload artifacts (windows)
        if: ${{ endsWith(matrix.target, '-windows') }}
        with:
          name: zvm-${{matrix.target}}
          path: zig-out/bin/zvm-${{matrix.target}}.exe

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-staging]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - run: |
          set -ex
          git config --local user.name 'ZVM Bot'
          git config --local user.email 'blaxoujunior@gmail.com'
          chmod +x artifacts/zvm-x86_64-linux/zvm-x86_64-linux
          version=$(artifacts/zvm-x86_64-linux/zvm-x86_64-linux --raw-version)
          # set outputs
          echo "version=$version" >> $GITHUB_OUTPUT
        id: git-version
      - name: compute hashes
        id: hashes
        working-directory: artifacts
        run: |
          set -ex
          for file in $(find . -type f -name "zvm-*"); do
            sha256sum $file > $file.sha256
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.git-version.outputs.version }}
          files: artifacts/*/*
          body: |
            Release ${{ steps.git-version.outputs.version }}
